// <auto-generated />
using HmiApi.Enums;
using HmiApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace HmiApi.Migrations
{
    [DbContext(typeof(HmiApiDbContext))]
    [Migration("20170823163156_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("HmiApi.Models.FileImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DestinationApplication");

                    b.Property<string>("FileName");

                    b.Property<string>("FilePath");

                    b.Property<string>("FileType");

                    b.Property<int>("Priority");

                    b.Property<string>("SourceApplication");

                    b.Property<int>("Status");

                    b.HasKey("Id");

                    b.ToTable("FileImport");
                });

            modelBuilder.Entity("HmiApi.Models.FileImportUserHelicopter", b =>
                {
                    b.Property<int>("FileImportId");

                    b.Property<int>("UserId");

                    b.Property<int>("HelicopterId");

                    b.HasKey("FileImportId", "UserId", "HelicopterId");

                    b.HasIndex("HelicopterId");

                    b.HasIndex("UserId");

                    b.ToTable("FileImportUserHelicopter");
                });

            modelBuilder.Entity("HmiApi.Models.Helicopter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<bool>("IsActive");

                    b.Property<string>("SerialNumber");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("Helicopter");
                });

            modelBuilder.Entity("HmiApi.Models.HelicopterPartNumber", b =>
                {
                    b.Property<int>("HelicopterId");

                    b.Property<int>("PartNumberId");

                    b.HasKey("HelicopterId", "PartNumberId");

                    b.HasIndex("PartNumberId");

                    b.ToTable("HelicopterPartNumber");
                });

            modelBuilder.Entity("HmiApi.Models.PartNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<string>("Number");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("PartNumber");
                });

            modelBuilder.Entity("HmiApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreationDate");

                    b.Property<string>("Email");

                    b.Property<bool>("IsActive");

                    b.Property<bool>("IsLocked");

                    b.Property<DateTime>("LockedDate");

                    b.Property<int>("LoginFailedTimes");

                    b.Property<string>("PasswordHash");

                    b.Property<int>("Role");

                    b.Property<string>("Username");

                    b.Property<bool>("isFirstLogin");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("HmiApi.Models.UserHelicopter", b =>
                {
                    b.Property<int>("UserId");

                    b.Property<int>("HelicopterId");

                    b.HasKey("UserId", "HelicopterId");

                    b.HasIndex("HelicopterId");

                    b.ToTable("UserHelicopter");
                });

            modelBuilder.Entity("HmiApi.Models.FileImportUserHelicopter", b =>
                {
                    b.HasOne("HmiApi.Models.FileImport", "FileImport")
                        .WithMany("FileImportsUsersHelicopters")
                        .HasForeignKey("FileImportId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HmiApi.Models.Helicopter", "Helicopter")
                        .WithMany("FileImportsUsersHelicopters")
                        .HasForeignKey("HelicopterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HmiApi.Models.User", "User")
                        .WithMany("FileImportsUsersHelicopters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HmiApi.Models.HelicopterPartNumber", b =>
                {
                    b.HasOne("HmiApi.Models.Helicopter", "Helicopter")
                        .WithMany("HelicoptersPartNumbers")
                        .HasForeignKey("HelicopterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HmiApi.Models.PartNumber", "PartNumber")
                        .WithMany("HelicoptersPartNumbers")
                        .HasForeignKey("PartNumberId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HmiApi.Models.UserHelicopter", b =>
                {
                    b.HasOne("HmiApi.Models.Helicopter", "Helicopter")
                        .WithMany("UsersHelicopters")
                        .HasForeignKey("HelicopterId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HmiApi.Models.User", "User")
                        .WithMany("UsersHelicopters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
